- name: Install nginx and run
  hosts: frontend
  become: yes #sudo acess
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started