- name: functions demo
  hosts: local
  connection: local
  vars:
    persons: "John,Tom,Ruby,Smith"
  tasks:
  - name: print default person name 
    ansible.builtin.debug:
      msg: "Hey, {{ person | default('Johnson') }}" 
  
  - name: print all persons
    ansible.builtin.debug:
      msg: "Hey, {{ persons | split (',') }}"     #split variables using delimitter

  - name: convert map to list
    vars:
      Team:
        Batter: Virat
        Bowler: John
        Fielder: Philips
    ansible.builtin.debug:
      msg: "Team is {{ Team | dict2items }}"  #conver map to list


  - name: convert list to map
    vars:
      Team:
      - {'key': 'Batter', 'value': 'Virat'}
      - {'key': 'Bowler', 'value': 'Bumrah'}
      - {'key': 'Fielder', 'value': 'Jadeja'}     
    ansible.builtin.debug:
      msg: "Team is {{ Team | items2dict }}"   # list to map

  - name: Convert to upper
    vars:
      name: Virat Kohli
    ansible.builtin.debug:
      msg: "Name is {{ name | upper }}"

  - name: Convert to lower
    vars:
      name: Virat Kohli
    ansible.builtin.debug:
      msg: "Name is {{ name | lower }}"
  
  
