- name: functions demo
  hosts: local
  connection: local
  vars:
    persons: "John, Tom, Ruby, Smith"
  tasks:
  - name: print default person name 
    ansible.builtin.debug:
      msg: "Hey, {{person | default('Johnson')}}"
  
  - name: print all persons
    ansible.builtin.debug:
      msg: "Hey, {{ persons }}"