- name: Install nginx
  hosts: dynamic_frontend
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: Pause for 10 seconds after installation
    ansible.builtin.pause:
      seconds: 10
  
  - name: Run and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    command: sleep 10
  
  - name: Pause for 10 seconds after installation
    ansible.builtin.pause:
      seconds: 10