- name: Install nginx
  hosts: dynamic_frontend
  become: yes
  serial: 4 #Which will run 4 instances at a time by grouping together and install and run and enable the nginx
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: Run and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  # - name: Pause for 10 seconds after installation
  #   ansible.builtin.pause:
  #     seconds: 10